services:
  gtnh-server:
    image: ghcr.io/maxtorm12138/gtnh-server:java25
    tty: true
    stdin_open: true
    network_mode: "host"
    userns_mode: keep-id
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
      EULA: "TRUE"
      TYPE: GTNH
      MEMORY: 8G
      GTNH_PACK_VERSION: "2.8.4"
      GTNH_DELETE_BACKUPS: FALSE
      SKIP_GTNH_UPDATE_CHECK: FALSE
      CREATE_CONSOLE_IN_PIPE: "true"
      LEVEL: GTNH-WORLD
      SERVER_PORT: 37000
      VIEW_DISTANCE: 16
      ENABLE_RCON: false
      WHITELIST: |
        maxtorm12138
      OPS: |
        maxtorm12138
    volumes:
      - ./config:/config
      - ./mods:/mods
      - ./serverutilities:/data/serverutilities
      - /data/save/GTNH-WORLD:/data/GTNH-WORLD
      - /data/backups:/data/backups
      - /data/server/:/data
